# Generated by Django 5.0.7 on 2024-07-30 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='katigoriya nomi')),
            ],
            options={
                'verbose_name': 'Categorylar',
                'verbose_name_plural': 'Category',
                'db_table': 'Categorys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqa',
                'db_table': 'Contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='yanglik nomi')),
                ('body', models.TextField(verbose_name="yanglik haqda ma'lumot")),
                ('image', models.ImageField(upload_to='news/image', verbose_name='Rasim')),
                ('publish_time', models.DateField(default=django.utils.timezone.now, verbose_name='yanglik yaratish vaqti')),
                ('create_time', models.DateField(auto_now=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Deactive', 'Faol emasa'), ('Active', 'Faol')], default='Deactive', max_length=50, verbose_name='Holati')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorymodel', verbose_name='katigoriyasi')),
            ],
            options={
                'verbose_name': 'Yangiliklar',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'News',
                'ordering': ['-publish_time'],
                'managed': True,
            },
        ),
    ]
