# Generated by Django 5.0.7 on 2024-07-31 04:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'managed': True, 'verbose_name': 'Kategoriyalar', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'managed': True, 'verbose_name': 'Aloqa', 'verbose_name_plural': 'Aloqalar'},
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='body',
            field=models.TextField(verbose_name="Yangilik haqda ma'lumot"),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorymodel', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='publish_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yangilik yaratish vaqti'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Yangilik nomi'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table='Categories',
        ),
    ]
